sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_2/0.bam2fa.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_3/0.te_repeat.blat.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_3/1.te_repeat.blat.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_4/step_4.MSU_r7.repeat.align.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/0.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/1.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/2.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/3.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/4.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/5.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/6.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/7.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/8.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/9.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/10.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_5/11.repeat.findSites.sh
sh /rhome/cjinfeng/BigData/00.RD/RILs/HEG4_mPing/RelocaTEi_HEG4.2.4/shellscripts/step_6/0.repeat.characterize.sh
