sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/0.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/1.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/2.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/3.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/4.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/5.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/6.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/7.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/8.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_2/9.fq2fq.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/0.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/1.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/2.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/3.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/4.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/5.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/6.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/7.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/8.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_3/9.te_repeat.blat.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_4/step_4.MSU_r7.repeat.align.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/0.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/1.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/2.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/3.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/4.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/5.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/6.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/7.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/8.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/9.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/10.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/11.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/0.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/1.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/2.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/3.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/4.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/5.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/6.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/7.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/8.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/9.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/10.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/11.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_7/0.repeat.characterize.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/clean_intermediate_files.sh
