sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_4/step_4.MSU_r7.repeat.align.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/0.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/1.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/2.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/3.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/4.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/5.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/6.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/7.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/8.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/9.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/10.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_5/11.repeat.findSites.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/0.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/1.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/2.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/3.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/4.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/5.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/6.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/7.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/8.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/9.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/10.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_6/11.repeat.absence.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/shellscripts/step_7/0.repeat.characterize.sh
sh /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/CAAS/Japonica_fastq_RelocaTEi/ERS467761_RelocaTEi/clean_intermediate_files.sh
