sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_2/0.bam2fa.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_3/0.te_repeat.blat.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_3/1.te_repeat.blat.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_4/step_4.MSU_r7.repeat.align.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/0.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/1.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/2.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/3.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/4.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/5.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/6.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/7.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/8.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/9.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/10.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_5/11.repeat.findSites.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/shellscripts/step_7/0.repeat.characterize.sh
sh /bigdata/stajichlab/cjinfeng/00.RD/RILs/Transpostion/bin/Manuscript_Preparation/Prepare0_HEG4_mPing/RelocaTE2_fq_RelocaTEi/HEG4.2.1_RelocaTEi/clean_intermediate_files.sh
